FROM registry.access.redhat.com/ubi9/ubi-minimal

ARG ANSIBLE_VERSION=2.16.17
ARG PYTHON_VERSION=3.11
ENV HOME=/projects/home

USER 0

COPY --chown=0:0 entrypoint.sh /
COPY --chown=0:0 set-cgroups.sh /

# Install base dependencies
RUN microdnf --disableplugin=subscription-manager install -y procps-ng openssl git \
        tar gzip zip xz shadow-utils bash podman podman-docker skopeo python${PYTHON_VERSION}-pip \
        python${PYTHON_VERSION}-devel python${PYTHON_VERSION}-requests jq wget which glibc-langpack-en \
        ca-certificates aardvark-dns fuse-overlayfs util-linux sudo ; \

    # Install ansible and related tools
    pip-${PYTHON_VERSION} install --no-cache-dir ansible-core==${ANSIBLE_VERSION} molecule==25.12.0 \
    molecule-plugins==25.8.12 ansible-lint==26.1.1 ansible-creator==25.12.0 \
    ansible-builder==3.1.1 \
    tox \
    pytest; \

    # Update complete image and cleanup
    microdnf update -y ; \
    microdnf clean all

RUN echo "user:x:1000:1000:devspaces user:${HOME}:/bin/bash" >> /etc/passwd ; \
    echo "user:x:1000:" >> /etc/group ; \
    chmod 600 /etc/shadow ; \
    echo "user:*:0:0:99999:7:::" >> /etc/shadow ; \
    echo "user:1001:64535" >> /etc/subuid ; \
    echo "user:1001:64535" >> /etc/subgid ; \
    setcap cap_setuid+ep /usr/bin/newuidmap ; \
    setcap cap_setgid+ep /usr/bin/newgidmap ; \
    echo "user ALL=NOPASSWD: /set-cgroups.sh" >> /etc/sudoers

USER 1000
ENTRYPOINT ["/usr/libexec/podman/catatonit","--","/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]
